apiVersion: v1
kind: Service
metadata:
  name: ms-eventos
  labels:
    app: ms-eventos
spec:
  type: NodePort
  selector:
    app: ms-eventos
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090